const User = require('../models/User');
const Complaint = require('../models/Complaint');

/**
 * @desc    Get all officers or filter by department
 * @route   GET /api/officers
 * @access  Private (Admin/Officer)
 */
const getOfficers = async (req, res) => {
  const { departmentId } = req.query;
  let query = { role: 'Department Officer' };

  if (departmentId) {
    query.department = departmentId;
  }

  try {
    const officers = await User.find(query)
      .select('-passwordHash')
      .populate('department', 'name');

    res.json({ success: true, count: officers.length, data: officers });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * @desc    Get officer stats and assigned workload summary
 * @route   GET /api/officers/:id/stats
 * @access  Private (Admin/Officer)
 */
const getOfficerStats = async (req, res) => {
  const officerId = req.params.id;

  try {
    const totalAssigned = await Complaint.countDocuments({ assignedOfficer: officerId });
    const inProgress = await Complaint.countDocuments({ assignedOfficer: officerId, status: 'In Progress' });
    const resolved = await Complaint.countDocuments({ assignedOfficer: officerId, status: 'Resolved' });
    const reported = await Complaint.countDocuments({ assignedOfficer: officerId, status: 'Reported' });

    res.json({
      success: true,
      data: {
        totalAssigned,
        inProgress,
        resolved,
        reported,
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * @desc    Get dashboard workload summary for logged in officer
 * @route   GET /api/officers/dashboard
 */
const getOfficerDashboard = async (req, res) => {
  try {
    const officerId = req.user._id;
    const totalAssigned = await Complaint.countDocuments({ assignedOfficer: officerId });
    const inProgress = await Complaint.countDocuments({ assignedOfficer: officerId, status: 'In Progress' });
    const resolved = await Complaint.countDocuments({ assignedOfficer: officerId, status: 'Resolved' });
    const closed = await Complaint.countDocuments({ assignedOfficer: officerId, status: 'Closed' });
    const escalated = await Complaint.countDocuments({ assignedOfficer: officerId, status: 'Escalated' });

    res.json({
      success: true,
      data: {
        totalAssigned,
        inProgress,
        resolved,
        closed,
        escalated,
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * @desc    Get all issues assigned to logged in officer
 * @route   GET /api/officers/issues
 */
const getOfficerIssues = async (req, res) => {
  try {
    const officerId = req.user._id;
    const issues = await Complaint.find({ assignedOfficer: officerId })
      .populate('citizen', 'fullName email mobile')
      .populate('department', 'name')
      .sort({ createdAt: -1 });

    res.json({
      success: true,
      count: issues.length,
      data: issues,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * @desc    Officer updates status of an issue
 * @route   PUT /api/officers/update-status
 */
const updateIssueStatus = async (req, res) => {
  const { complaintId, status, notes } = req.body;
  try {
    const { changeStatus } = require('../services/complaintService');
    const complaint = await changeStatus(complaintId, status, notes, req.user._id);
    res.json({ success: true, data: complaint });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * @desc    Officer uploads resolution proof notes and images
 * @route   POST /api/officers/upload-resolution
 */
const uploadResolution = async (req, res) => {
  const { complaintId, notes } = req.body;
  const resolutionImages = req.files ? req.files.map((file) => file.path || `/uploads/${file.filename}`) : [];

  try {
    const { resolutionProcessing } = require('../services/officerService');
    const complaint = await resolutionProcessing(complaintId, notes, resolutionImages);
    res.json({ success: true, data: complaint });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * @desc    Get performance reports generated by officer
 * @route   GET /api/officers/reports
 */
const getOfficerReports = async (req, res) => {
  try {
    const Report = require('../models/Report');
    const reports = await Report.find({ generatedBy: req.user._id }).sort({ createdAt: -1 });
    res.json({ success: true, count: reports.length, data: reports });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

module.exports = {
  getOfficers,
  getOfficerStats,
  getOfficerDashboard,
  getOfficerIssues,
  updateIssueStatus,
  uploadResolution,
  getOfficerReports,
};
